---
# tasks file for r_write_local_state_facts
  - block:
    - name: "set local fact last_run = {{ pl_name }}"
      ini_file:
        path: "/etc/ansible/facts.d/state.fact"
        section: state  
        option: last_run
        value: "{{ pl_name }}"
        state: present
        backup: yes

    - name: "set local fact all_run"
      replace:
        backup: yes
        dest: "/etc/ansible/facts.d/state.fact"
        regexp: '^(all_run(?!.*\b{{ pl_name }}\b).*)$'
        replace: '\1,{{ pl_name }}'

    - name: "set local fact last_deploy = {{ lookup('pipe','date +%H:%M:%S-%d.%m.%Y') }}"
      ini_file:
        path: "/etc/ansible/facts.d/state.fact"
        section: state  
        option: last_deploy
        value: "{{ lookup('pipe','date +%H:%M:%S-%d.%m.%Y') }}-{{ pl_name }}"
        state: present
        backup: yes

    rescue:
    - fail:
        msg: "error writing state fact"

    tags:
    - always
