---
# tasks file for r_update_all
  - block:
    - name: "update all packages"
      yum:
        name: "*"
        state: latest

    rescue:
    - fail:
        msg: "error: update all rpm's from configured repos"

    tags:
    - update_all
