---
# tasks file for r_configure_selinux
  - block:
    - name: "configure selinux - set state: {{ selinux.state }}"
      selinux:
        policy: "{{ selinux.policy }}"
        state: "{{ selinux.state }}"

    rescue:
    - fail:
        msg: "error: configure selinux"

    tags:
    - configure_selinux
