---
# tasks file for r_password_policies
  - block:
    - name: "install pam module"
      package:
        name: "{{ item }}"
        state: present
      loop:
        - pam
        - pam-devel

    - name: "set password reuse"
      replace:
        dest: /etc/pam.d/system-auth
        regexp: '^(password.*pam_unix.so(?!.*\bremember\b).*)$'
        replace: '\1 remember=12' 

    - name: "set password hash"
      command: authconfig --passalgo=sha512 --update

    - name: "set password complexity"
      lineinfile:
        dest: /etc/pam.d/system-auth
        state: present
        regexp: '^(password.*pam_pwquality.so.*)$'
        line: "password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 minlen=8 dcredit=-1 ucredit=-1 ocredit=-1 lcredit=-1 authtok_type="

    rescue:
    - fail:
        msg: "set password policies failed"

    tags:
    - password_policies
