################################################
---
- name: "configure apache webserver at {{ ansible_play_hosts | to_yaml }}"
  hosts: "{{ group_name | default('all') }}"
  gather_facts: no
  any_errors_fatal: true
  become: yes
  vars:
    pl_name: "configure_apache"

################################################
  pre_tasks:
  - block:
    - name: "role check availibility"
      include_role:
        name: r_check_availability

    - name: "role check node os"
      include_role:
        name: r_check_os

    - name: "role create local facts"
      include_role:
        name: r_create_local_facts

    rescue:
    - fail:
        msg: "pre tasks {{ pl_name }} failed"

    tags:
    - always


################################################
  tasks:
  - block:
    - name: "role add filesystem to apache configuration"
      include_role:
        name: r_add_filesystem
      tags: 
      - add_filesystem

    - name: "role install apache "
      include_role:
        name: r_setup_apache
      tags: 
      - setup_apache

    rescue:
    - fail:
        msg: "tasks {{ pl_name }} failed"

################################################
  post_tasks:
  - block:
    - name: "role write local state facts"
      include_role:
        name: r_write_local_state_facts
      tags:
      - always

    rescue:
    - fail:
        msg: "post tasks {{ pl_name }} failed"
