---
# tasks file for r_check_4_rhel
# get facts
  - block:
    - name: "reload facts"
      setup:
#        gather_subset:
#          - '!all'
#          - '!any'
#          - facter

    - name: "set runtime distribution flag" 
      set_fact:
        runtime_dist_flag: "{{ ansible_distribution|lower }} -{{ ansible_distribution_major_version }}"

    - name: "display runtime distribution flag"
      debug:
        msg: "{{ ansible_host }}:{{ runtime_dist_flag }}"
      
    rescue:
    - fail:
        msg: "error: during check node os"

    tags:
    - always
